/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gourmand.gui;

import java.text.ParseException;
import javax.swing.JOptionPane;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author user
 */
public class AcceuilClient_Gui extends javax.swing.JFrame {

    /**
     * Creates new form AcceuilClient_Gui
     */
    public AcceuilClient_Gui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Menu_Gestion_Compte = new javax.swing.JMenuItem();
        Menu_Quitter = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        Menu_Gestion_EG = new javax.swing.JMenuItem();
        Menu_ContacterAdmin = new javax.swing.JMenuItem();

        jMenuItem5.setText("jMenuItem5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Edit");

        Menu_Gestion_Compte.setText("Gestion Compte");
        Menu_Gestion_Compte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_Gestion_CompteActionPerformed(evt);
            }
        });
        jMenu1.add(Menu_Gestion_Compte);

        Menu_Quitter.setText("Quitter");
        Menu_Quitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_QuitterActionPerformed(evt);
            }
        });
        jMenu1.add(Menu_Quitter);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Opérations Client");

        Menu_Gestion_EG.setText("Consulter Les Espaces Gourmand");
        Menu_Gestion_EG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_Gestion_EGActionPerformed(evt);
            }
        });
        jMenu2.add(Menu_Gestion_EG);

        Menu_ContacterAdmin.setText("Contacter Administrateur");
        jMenu2.add(Menu_ContacterAdmin);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Menu_Gestion_CompteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_Gestion_CompteActionPerformed
        // TODO add your handling code here:
        ModifierCompteClient_GUI a = new ModifierCompteClient_GUI();
        this.setVisible(false);
        a.setVisible(true);
    }//GEN-LAST:event_Menu_Gestion_CompteActionPerformed

    private void Menu_QuitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_QuitterActionPerformed
        // TODO add your handling code here:
     /*   int p = JOptionPane.showConfirmDialog(null, "Voulez-vous Quitter l'application?", "Confirmation", JOptionPane.YES_NO_OPTION);
        if (p == 0) {
            this.dispose();
            Bienvenue_GUI a = null;
            a = new Bienvenue_GUI();

            a.setVisible(true);
        }
        System.exit(0);*/
    }//GEN-LAST:event_Menu_QuitterActionPerformed

    private void Menu_Gestion_EGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_Gestion_EGActionPerformed
        // TODO add your handling code here:
        ClientListeEG_GUI CL= new ClientListeEG_GUI();
        this.setVisible(false);
        CL.setVisible(true);
    }//GEN-LAST:event_Menu_Gestion_EGActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AcceuilClient_Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AcceuilClient_Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AcceuilClient_Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AcceuilClient_Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AcceuilClient_Gui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Menu_ContacterAdmin;
    private javax.swing.JMenuItem Menu_Gestion_Compte;
    private javax.swing.JMenuItem Menu_Gestion_EG;
    private javax.swing.JMenuItem Menu_Quitter;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem5;
    // End of variables declaration//GEN-END:variables
}
