/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gourmand.gui;

import gourmand.dao.EspaceGourmandDAOHAJER;
import gourmand.util.MyConnection;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author hajer.BENSALEM
 */
public class GestionEspaceGourmandHAJER extends javax.swing.JFrame {
public static Connection conn;
    /**
     * Creates new form GestionEspaceGourmand
     */
    public GestionEspaceGourmandHAJER() {
        initComponents();
    }

  
                
                 
           
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("supprimer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Ajouter");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Retour");

        jButton4.setText("Contacter");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jTable1.setModel(new MyTableModel());
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(85, 85, 85)
                            .addComponent(jButton4))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton1)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addGap(67, 67, 67)
                        .addComponent(jButton2)
                        .addGap(47, 47, 47)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(14, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void TableGPEGMouseClicked(java.awt.event.MouseEvent evt) {                                       
        int rows = jTable1.getSelectedRow();
        String a=jTable1.getModel().getValueAt(rows, 1).toString();
        System.out.println(a);
        try {
            Statement st =(Statement) MyConnection.getInstance().conn.createStatement();
            int row = jTable1.getSelectedRow();
            String Table_Click =(jTable1.getModel().getValueAt(row, 1).toString());
            String sql = "select nom,prenom,ok from reservation where nom='"+ Table_Click+"'";
            ResultSet res = st.executeQuery(sql);
            while(res.next())
            {
                
            }
        } catch (SQLException ex) {
            Logger.getLogger(GestionReservationJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       // Statement state = conn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
      EspaceGourmandDAOHAJER D =new EspaceGourmandDAOHAJER();
      EspaceGourmandDAOHAJER RDAO = new EspaceGourmandDAOHAJER();
        
      //RDAO.supprimer(D);
                  
    // jTable1.addMouseListener();
     //jButton1.addMouseListener((new java.awt.event.MouseAdapter() {} ));
    
       try {
                Class.forName("com.mysql.jdbc.Driver");
           
                        System.out.println("DRIVER OK ! ");
                         
                        String url = "jdbc:mysql://127.0.0.1:3306/projet_restaurant";
                        String user = "root";
                        String passwd = "";
                         
                        Connection conn = DriverManager.getConnection(url, user, passwd);
                        conn.setAutoCommit(true);
                        System.out.println("Connection effective !");
                        Statement state = conn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
        
        int lign=   jTable1.getSelectedRow();
     //int col = jTable1.getSelectedColumn();
     Object b = jTable1.getValueAt(lign,lign);
      System.out.println(b);
      // jButton1.addActionListener(new java.awt.event.MouseAdapter() {});
       jButton1.addActionListener(new ActionListener(){
                public void actionPerformed(ActionEvent arg0) {    
                    setVisible(true );
                }
            });
      state.executeUpdate("DELETE  FROM espacegourmand WHERE nomEspaceGourmand  ='"+b+"'");
                                                System.out.println("voila C fé");
    
     
        
        ////jTable1.removeRowSelectionInterval(lign, 
           //     lign);
         System.out.println(b);
       // jTable1.repaint();
         } catch (Exception e1) {
                        e1.printStackTrace();
                         }
                
            jTable1.setModel(new MyTableModel());

            
        /*jT.getSelectedColumn();
                       
                        state.executeUpdate("DELETE  FROM serveur WHERE cle ='"+b+"' ");
                                                System.out.println("voila C fé");
                      
                        }catch (Exception e1) {
                        e1.printStackTrace();}*/

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         GererEspaceGourmandHAJER gerer = new GererEspaceGourmandHAJER();
        gerer.setVisible(true);
        this.setVisible(false);
                            
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionEspaceGourmandHAJER().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
