/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gourmand.gui;

import gourmand.dao.BoissonDAO;
import gourmand.dao.DessertDAO;
import gourmand.dao.EntreeDAO;
import gourmand.dao.MenuDAO;
import gourmand.dao.PlatDAO;
import gourmand.entities.Boissons;
import gourmand.entities.Desserts;
import gourmand.entities.Entrees;
import gourmand.entities.Menu;
import gourmand.entities.Plats;
import gourmand.util.MyConnection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Mahdouch
 */
public class ModificationMenuJFrame extends javax.swing.JFrame {

    /**
     * Creates new form ModificationMenuJFrame
     */
    public ModificationMenuJFrame() {
        initComponents();
        
        if(radioEntree.isSelected())
            remplirEntrees();
        if(radioPlat.isSelected())
            remplirPlats();
        if(radioDessert.isSelected())
            remplirDesserts(); 
        if(radioBoisson.isSelected())
            remplirBoissons();
    }
    
    public void remplirEntrees(){
        List<Entrees> listEntrees = new ArrayList<Entrees>();
        EntreeDAO entreeDAO = new EntreeDAO();
        listEntrees = entreeDAO.display();
        for(Entrees e:listEntrees){
            Combo.addItem(e.getLibelleEntree());
        }
        
    }
    
    public void remplirPlats(){
        List<Plats> listPlats = new ArrayList<Plats>();
        PlatDAO platDAO = new PlatDAO();
        listPlats = platDAO.display();
        for(Plats p:listPlats){
            Combo.addItem(p.getLibellePlat());
        }
        
    }
    
    public void remplirDesserts(){
        List<Desserts> listDesserts = new ArrayList<Desserts>();
        DessertDAO dessertDAO = new DessertDAO();
        listDesserts = dessertDAO.display();
        for(Desserts d:listDesserts){
            Combo.addItem(d.getLibelleDessert());
        }
        
    }
    
    public void remplirBoissons(){
        List<Boissons> listBoissons = new ArrayList<Boissons>();
        BoissonDAO boissonDAO = new BoissonDAO();
        listBoissons = boissonDAO.display();
        for(Boissons b:listBoissons){
            Combo.addItem(b.getLibelleBoisson());
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        Combo = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtLibelle = new javax.swing.JTextField();
        txtPrix = new javax.swing.JTextField();
        txtMenu = new javax.swing.JTextField();
        butModifierMenu = new javax.swing.JButton();
        butAjouterMenu = new javax.swing.JButton();
        butRetour = new javax.swing.JButton();
        butReset = new javax.swing.JButton();
        radioEntree = new javax.swing.JRadioButton();
        radioPlat = new javax.swing.JRadioButton();
        radioDessert = new javax.swing.JRadioButton();
        radioBoisson = new javax.swing.JRadioButton();

        jLabel3.setText("Menu :");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel13.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 153, 204));
        jLabel13.setText("Modifier Le Menu De Mon Espace Gourmand ");

        Combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboActionPerformed(evt);
            }
        });

        jLabel1.setText("Libelle : ");

        jLabel2.setText("Prix :");

        jLabel4.setText("Menu :");

        txtLibelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLibelleActionPerformed(evt);
            }
        });

        butModifierMenu.setText("Modifier");
        butModifierMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butModifierMenuActionPerformed(evt);
            }
        });

        butAjouterMenu.setText("Ajouter");
        butAjouterMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butAjouterMenuActionPerformed(evt);
            }
        });

        butRetour.setText("Retour");
        butRetour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butRetourActionPerformed(evt);
            }
        });

        butReset.setText("Reset");
        butReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butResetActionPerformed(evt);
            }
        });

        buttonGroup1.add(radioEntree);
        radioEntree.setText("  Entrees");
        radioEntree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioEntreeActionPerformed(evt);
            }
        });

        buttonGroup1.add(radioPlat);
        radioPlat.setText("  Plats");
        radioPlat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioPlatActionPerformed(evt);
            }
        });

        buttonGroup1.add(radioDessert);
        radioDessert.setText("  Desserts");
        radioDessert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioDessertActionPerformed(evt);
            }
        });

        buttonGroup1.add(radioBoisson);
        radioBoisson.setText("  Boissons");
        radioBoisson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBoissonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtLibelle, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtPrix, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(205, 205, 205))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(radioDessert)
                                    .addComponent(radioEntree))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(radioPlat)
                                    .addComponent(radioBoisson))
                                .addGap(71, 71, 71)
                                .addComponent(Combo, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(111, 111, 111))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(butModifierMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(butAjouterMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(butReset, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butRetour, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 124, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Combo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(radioEntree)
                            .addComponent(radioPlat))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(radioDessert)
                            .addComponent(radioBoisson))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLibelle, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPrix, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(butReset, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butModifierMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butAjouterMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butRetour, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtLibelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLibelleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLibelleActionPerformed

    private void butRetourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butRetourActionPerformed
        ModificationEspaeGourmandJFrame modifEspaceGourmand = new ModificationEspaeGourmandJFrame();
        modifEspaceGourmand.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_butRetourActionPerformed

    private void butResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butResetActionPerformed
        txtLibelle.setText(null);
        txtPrix.setText(null);
        txtMenu.setText(null);
    }//GEN-LAST:event_butResetActionPerformed

    private void butAjouterMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butAjouterMenuActionPerformed
        MenuDAO EGDAO = new MenuDAO();
        Menu m = new Menu();
        
        EntreeDAO EntDAO = new EntreeDAO();
        Entrees E = new Entrees();
        
        PlatDAO PDAO = new PlatDAO();
        Plats P = new Plats();
        
        DessertDAO DDAO = new DessertDAO();
        Desserts D = new Desserts();
        
        BoissonDAO BDAO = new BoissonDAO();
        Boissons B = new Boissons();
        
        if(radioEntree.isSelected())
        {
            E.setLibelleEntree(txtLibelle.getText());
            E.setPrix(Integer.parseInt(txtPrix.getText()));
            EntDAO.ajouter(E);
        }
        
        if(radioPlat.isSelected())
        {
            P.setLibellePlat(txtLibelle.getText());
            P.setPrix(Integer.parseInt(txtPrix.getText()));
            PDAO.ajouter(P);
        }
        
        if(radioDessert.isSelected())
        {
            D.setLibelleDessert(txtLibelle.getText());
            D.setPrix(Integer.parseInt(txtPrix.getText()));
            DDAO.ajouter(D);
        }
        
        if(radioBoisson.isSelected())
        {
            remplirBoissons();
            B.setLibelleBoisson(txtLibelle.getText());
            B.setPrix(Integer.parseInt(txtPrix.getText()));
            EntDAO.ajouter(B);
        }
        
    }//GEN-LAST:event_butAjouterMenuActionPerformed

    private void radioPlatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioPlatActionPerformed
        remplirPlats();
    }//GEN-LAST:event_radioPlatActionPerformed

    private void radioEntreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioEntreeActionPerformed
        remplirEntrees();
    }//GEN-LAST:event_radioEntreeActionPerformed

    private void radioBoissonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBoissonActionPerformed
        remplirBoissons();
    }//GEN-LAST:event_radioBoissonActionPerformed

    private void radioDessertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioDessertActionPerformed
        remplirDesserts();
    }//GEN-LAST:event_radioDessertActionPerformed

    private void butModifierMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butModifierMenuActionPerformed
        EntreeDAO EntDAO = new EntreeDAO();
        Entrees E = new Entrees();
        
        PlatDAO PDAO = new PlatDAO();
        Plats P = new Plats();
        
        DessertDAO DDAO = new DessertDAO();
        Desserts D = new Desserts();
        
        BoissonDAO BDAO = new BoissonDAO();
        Boissons B = new Boissons();
        
        if(radioEntree.isSelected())
        {
            E.setLibelleEntree(txtLibelle.getText());
            E.setPrix(Integer.parseInt(txtPrix.getText()));
            EntDAO.modifier(E);
        }
        
        if(radioPlat.isSelected())
        {
            P.setLibellePlat(txtLibelle.getText());
            P.setPrix(Integer.parseInt(txtPrix.getText()));
            PDAO.modifier(P);
        }
        
        if(radioDessert.isSelected())
        {
            D.setLibelleDessert(txtLibelle.getText());
            D.setPrix(Integer.parseInt(txtPrix.getText()));
            DDAO.modifier(D);
        }
        
        if(radioBoisson.isSelected())
        {
            B.setLibelleBoisson(txtLibelle.getText());
            B.setPrix(Integer.parseInt(txtPrix.getText()));
            EntDAO.modifier(B);
        }
    }//GEN-LAST:event_butModifierMenuActionPerformed

    private void ComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboActionPerformed
        /*List<Boissons> listBoissons = new ArrayList<Boissons>();
        BoissonDAO boissonDAO = new BoissonDAO();
        
        List<Plats> listPlats = new ArrayList<Plats>();
        PlatDAO platDAO = new PlatDAO();
        
        List<Entrees> listEntrees = new ArrayList<Entrees>();
        EntreeDAO entreeDAO = new EntreeDAO();
        
        List<Desserts> listDesserts = new ArrayList<Desserts>();
        DessertDAO dessertDAO = new DessertDAO();*/
        String requetP = "select libellePlat,prix,idMenu from plats where libellePlat =" + Combo.getSelectedItem();
        try {
            Statement st =(Statement) MyConnection.getInstance().conn.createStatement();
            ResultSet res = st.executeQuery(requetP);
            while(res.next())
            {
                String add0 = res.getString("Nom Espace Gourmand");
                txtLibelle.setText(add0);
                String add1 = res.getString("Adresse");
                txtPrix.setText(add1);
                String add2 = res.getString("Téléphone");
                txtMenu.setText(add2);
                
            }
        } catch (SQLException ex) {
            Logger.getLogger(ModificationMenuJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ComboActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificationMenuJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificationMenuJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificationMenuJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificationMenuJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModificationMenuJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox Combo;
    private javax.swing.JButton butAjouterMenu;
    private javax.swing.JButton butModifierMenu;
    private javax.swing.JButton butReset;
    private javax.swing.JButton butRetour;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton radioBoisson;
    private javax.swing.JRadioButton radioDessert;
    private javax.swing.JRadioButton radioEntree;
    private javax.swing.JRadioButton radioPlat;
    private javax.swing.JTextField txtLibelle;
    private javax.swing.JTextField txtMenu;
    private javax.swing.JTextField txtPrix;
    // End of variables declaration//GEN-END:variables
}
