/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gourmand.gui;


import gourmand.dao.MailClient;
import gourmand.dao.MailPropEG;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import org.jfree.ui.RefineryUtilities;
import mail.*;

 /*
 * @author BaSeif
 */
public class MotdePasseOublie extends javax.swing.JFrame {
    
 
    Mail mail = new Mail();
        
    /**
     * Creates new form motdepasseoublie
     */
    public MotdePasseOublie() {
        initComponents();
        
        RefineryUtilities.centerFrameOnScreen(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor. client !1 Prop 0
     *                                 client 0 prop !1 
     *                                  
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_mail_pass = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cmd_mail_passe = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mot de Passe Oublié");
        setAlwaysOnTop(true);
        setPreferredSize(new java.awt.Dimension(540, 430));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setText("Nous pouvons vous aider à retrouver votre mot de passe ");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 130, 550, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 255));
        jLabel4.setText("Mot de passe oublié ?");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(150, 30, 270, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setText("Réaccéder à votre compte");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 90, 260, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel6.setText("à l’aide de votre adresse électronique associée à votre compte.");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 160, 580, 20);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/courriel_icone.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(380, 190, 130, 120);

        txt_mail_pass.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(txt_mail_pass);
        txt_mail_pass.setBounds(60, 250, 230, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Entrez votre adresse email ");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(40, 220, 210, 20);

        cmd_mail_passe.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmd_mail_passe.setText("Envoyer");
        cmd_mail_passe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_mail_passeActionPerformed(evt);
            }
        });
        getContentPane().add(cmd_mail_passe);
        cmd_mail_passe.setBounds(70, 320, 130, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/background0.gif"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 534, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmd_mail_passeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_mail_passeActionPerformed
        // TODO add your handling code here:
       
        mail.setMailAddressRecipient(txt_mail_pass.getText());
        mail.setMailAddressSender("tounsi.gourmand@gmail.com");
        mail.setPwd("O2tounsi");
       
               
        mail.setMailSubject("Tounsi Gourmand:Réinitialiser/Récupérer votre mot de passe ");
      
        
        
        
        if (!(txt_mail_pass.getText().isEmpty()))
            
            
        {
            MailClient MaCl = new MailClient();
            MailPropEG MaPr = new MailPropEG();
            
            
            String x = MaCl.MailClientPasse(txt_mail_pass.getText());
            String a = MaCl.MailClientlogin(txt_mail_pass.getText());
            
            String y=  MaPr.MailPropEGPasse(txt_mail_pass.getText());
            String b=  MaPr.MailPropEGLogin(txt_mail_pass.getText());
            
       
            if ((x!=null) || (y!=null))
        {
             //Envoi de mail @  
        String msg="Tounsi Gourmand a reçu une demande pour retrouver le mot de passe de votre compte. \n" +
        "\n # Votre mot de passe est : ";           
            if (x!=null)
            {  msg=(msg+" "+x);
          //System.out.println("msg X \n"+msg);
            }else if (y!=null)
            {   msg=(msg+" "+y );
           // System.out.println("msg Y \n"+msg);
            }
      
            msg =(msg+"\n # Votre Login est : ");
            if (a!=null)
            {  msg=(msg+" "+a);
          //System.out.println("msg X \n"+msg);
            }else if (b!=null)
            {   msg=(msg+" "+b );
           // System.out.println("msg Y \n"+msg);
            }
        
            
            
        msg=(msg+"\n============================================================"
                +"\n  Si vous recevez beaucoup d'emails de réinitialisation de mot de passe que "
                +"vous n'avez pas demandés, vous pouvez changer vos paramètres de compte afin d'exiger "
                +"une information personnelle pour pouvoir débuter une réinitialisation de mot de passe."
                +"\n\n\n============================================================"
                + "\n  Veuillez ne pas répondre à ce message ; il a été envoyé à partir d'une boîte automatisée."
                +"\n Ce message est lié à votre utilisation de Tounsi Gourmand" );
        
        mail.setMailObject(msg);
        
            
            System.out.println("finale msg \n"+msg );
         
        MailConstruction mc = new MailConstruction();
        mc.getMailProperties();
        mc.getMailMessage(mail);
        mc.SendMessage();
        System.out.println("OK c bon ");
            
        
        
           Icon image = new ImageIcon( getClass().getResource("/img/mail.png"));     
           JOptionPane.showMessageDialog(this,"Nous avons envoyé les instructions de récuperation \nde mot de passe à votre adresse email : "
                   +txt_mail_pass.getText()
                   + "\n\nSi vous ne recevez pas les instructions d'ici une minute ou deux, \nvérifiez les filtres de spams et de courriers indésirables de votre compte","Réinitialiser le mot de passe",
           JOptionPane.OK_OPTION, image);
           
            Authentification Aut= null;
            Aut = new Authentification();
            this.setVisible(false);
            Aut.setVisible(true);
           
        }
            else {
            Icon image = new ImageIcon( getClass().getResource("/img/interdit.png"));     
           JOptionPane.showMessageDialog(this,"L’adresse électronique ne correspond à aucun compte."
                   + "\n Avez-vous vraiment un compte ?"," Erreur de l'Adresse mail  ",
            JOptionPane.OK_OPTION, image);
                
            }
        
    }//GEN-LAST:event_cmd_mail_passeActionPerformed
    
    else {
            JOptionPane.showMessageDialog(this, "Champs Vides !!");
        }
    
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MotdePasseOublie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MotdePasseOublie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MotdePasseOublie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MotdePasseOublie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MotdePasseOublie().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmd_mail_passe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txt_mail_pass;
    // End of variables declaration//GEN-END:variables
}
